# Generated by Django 5.2.12 on 2026-03-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='material',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='material',
            name='total_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
